### ISSUE TITLE
Library is complex to use

### ISSUE THREAD

**Issue by glennposadas** [Vkt0r/AccordionMenuSwift#12]
Hi Vkt0r,

I see that you say this is the best way to implement accordion. Anyway, your codes in this library and in the sample project, I find it hard to understand. Is it possible for you to make a very simple sample project that teaches how to add data properly? I will try my best to make one in the future if by any chance I get to understand your codes. I found another Accordion library and its so easy to use and implement, however it has bugs with regards to cells being reused (trying to fix them by myself by the way).

So again, thanks for this, but I'm just requesting for a quite easier to read sample project.

Glenn

**Comment by tahaSuleyman** [comment]
@glennposadas What do you want to implement? What sort of project will you use it to be more clear. Tell me what you want so maybe I can help you :) Have a nice day.

**Comment by adairrojas** [comment]
Hi Vkt0r could you help me to run a demo project??. I'm not get running the project or use in any other projects, the Xcode message is that Accordion framework cannot load image,i ‘ve already embed binary on my project, could you send me instructions step by step how to integrate the library? Any help would be appreciated

thank you so much!!

**Comment by Vkt0r** [comment]
Hi @adairrojas, yes of course I'll try to update the project with a demo project as soon as possible with an example.

**Comment by Vkt0r** [comment]
@adairrojas I've integrated CocoaPods support for the library and inside the project, I added an example project of use of the library. Sorry for the delay 😅. I hope this help you.

**Comment by jbhav24** [comment]
Cocoapods is not working at the moment. Doesn't come up on their site and doesn't work properly when I do "pod install"

**Comment by Vkt0r** [comment]
@jbhav24 Sorry about that ☹️, I work on it tomorrow to see what's happening

**Comment by Vkt0r** [comment]
@jbhav24 Cocopods it'w working properly now in the project, please let me know if detect any trouble

**Comment by Vkt0r** [comment]
@glennposadas I think now you can see a full example of how to use the library, sorry for the time it take me to update it
