### ISSUE TITLE
Cell without children?

### ISSUE THREAD

**Issue by WebElg** [Vkt0r/AccordionMenuSwift#21]
Is there a way to have a cell without children?
How can I achieve that first three cells have children, and last two don't?

**Comment by Vkt0r** [comment]
@WebElg Yes, of course, you can, the only thing you need to do is pass an empty array as argument for the child's array, using the example project should be something like this:

    let item1 = Parent(state: .collapsed, childs: ["SubItem 1", "SubItem 2", "SubItem 3"], title: "Item 1")
    let item2 = Parent(state: .collapsed, childs: ["SubItem 1", "SubItem 2"], title: "Item 2")
    let item3 = Parent(state: .collapsed, childs: ["SubItem 1", "SubItem 2", "SubItem 3"], title: "Item 3")
    let item4 = Parent(state: .collapsed, childs: ["SubItem 1", "SubItem 2"], title: "Item 4")
    let item5 = Parent(state: .collapsed, childs: [], title: "Item 5")  // No child cells
        
    dataSource = [item1, item2, item3, item4, item5]
    numberOfCellsExpanded = .several
    total = dataSource.count

I'm working on an update for the library that simplifies the process and support for listening to selections in the cell, customs cells, etc. I think it should be ready soon.

I hope this help you

**Comment by WebElg** [comment]
Thank you for your help, it works great.
